Export/Import Logins
SinghSaubhik/CryptoKeep pull request #51
Opened 2021-04-20 04:55 UTC by KirbyNguyen

I have implemented a way for the user to export all the logins into a JSON file. The app will also be able to read from this JSON file and add the data back into the database.
Some shortcomings: the user cannot choose the location nor the name of the export and import file. Right now, the file will be defaulted to "loginData.json." Additionally, the import will delete everything in the database before repopulating it. 

P/S: I was working on this one in my fork so there's no branch with the issue name :( sorry

2021-04-21 02:00 UTC, SinghSaubhik commented
> I have implemented a way for the user to export all the logins into a JSON file. The app will also be able to read from this JSON file and add the data back into the database.
> Some shortcomings: the user cannot choose the location nor the name of the export and import file. Right now, the file will be defaulted to "loginData.json." Additionally, the import will delete everything in the database before repopulating it.
> 
> P/S: I was working on this one in my fork so there's no branch with the issue name :( sorry

I will look into it, thanks for PR

2021-04-22 10:43 UTC, SinghSaubhik approved these changes

2021-04-22 10:43 UTC, singhsaubhik commented on lib/components/local_path.dart
> +  static final LocalPath instance = LocalPath._privateConstructor();
Move this to service directory and rename this file as `file_service.dart`

2021-04-22 10:43 UTC, singhsaubhik commented on lib/components/local_path.dart
> +  final String path = "assets";
It seems this is not used anywhere

2021-04-22 10:45 UTC, SinghSaubhik requested changes
ARR

2021-04-22 18:42 UTC, KirbyNguyen commented on lib/components/local_path.dart
> +  final String path = "assets";
I have removed that from the code

2021-04-22 18:42 UTC, KirbyNguyen commented on lib/components/local_path.dart
> +  static final LocalPath instance = LocalPath._privateConstructor();
Just moved it to services

2021-04-22 18:47 UTC, KirbyNguyen commented
I don't know if the new commit shows on here, should I make a new pull request?

2021-04-23 05:43 UTC, SinghSaubhik approved these changes

2021-04-23 05:43 UTC, merged